### PR TITLE
force registered element to inherit from HTMLElement

### PR DESCRIPTION
**Pull request by kelvinss**

### CODE REVIEW

**Comment by csuwildcat** [comment]
Not sure I understand here. We automatically register elements with the prototype of HTMLElement if you don't specify one, or the prototype of the native element if you extend it. What is this providing beyond the existing default inheritance from HTMLElement?

**Comment by kelvinss** [comment]
Apparently, the prototype of the native element is used by default, but _only_ if I don't specify one. With this code, the registered element will inherit from `HTMLElement` even if I specify a prototype that does not, which (I think) is the expected behavior.

Maybe this feature could be enabled through a parameter passed to xtag. This could also be used for another feature that I need, that is registering custom elements for a specific `document` object, such as one inside an iframe.

I was thinking about wrapping the module code inside something like this:

```js
var init = function (opts){
    if (typeof opts === 'undefined'){ opts = {}; }
    var win = opts.window || window,
        doc = opts.document || win.document || document,
        forceHTMLElementInherit = opts.forceHTMLElementInherit || false,
    "..."
    var xtag = {
        "..."
    }
    "..."
    return xtag;
};
init();
```
And then use it like this:
```js
_xtag = xtag.init( {
    forceHTMLElementInherit: true,
    window: myIframe.contentWindow
} );
```
What do you think?

**Comment by kelvinss** [comment]
https://github.com/kelvinss/x-tag-core/commit/f3b8088fc135bcc8c133f297699345b90d7d640e

**Comment by csuwildcat** [comment]
I see the issue now, I am not sure why we didn't catch that flow/need earlier. I will either pull your changes in, or do something like it to enable what you want (have to check all our tests first, etc.)

**Comment by csuwildcat** [comment]
Thank you for uncovering this @kelvinss

**Comment by csuwildcat** [comment]
I just got back from a long trip to NYC; I will address this today.

**Comment by csuwildcat** [comment]
@kelvinss can you checkout this branch and let me know if it does what you desire? --> https://github.com/x-tag/core/tree/custom-proto

**Comment by kelvinss** [comment]
Looks like it just ignores `basePrototype` if the `'extends'`options is passed, or if it doesn't inherit from `HTMLElement`:
```js
'prototype': extended ?
	Object.create(
		Object.create(doc.createElement(extended).constructor).prototype, // basePrototype ?
		tag.prototype
	) :
	basePrototype instanceof elementProto.constructor ?
		basePrototype :
		Object.create(elementProto, tag.prototype) // basePrototype ?
```

The behavior I was trying to get is automatically extending the native prototype with `basePrototype`, if it doesn't inherit the native prototype already. So:

```js
Elem = xtag.register('x-p', {
	'extends': 'p',
	prototype: {   // does not inherit HTMLParagraphElement
		someVar: true
	}
});

p = new Elem();
console.log( p instanceof HTMLParagraphElement );  // true
console.log( p.someVar );  // true
```

Is there a simple way to extend the prototypes? Using `Object.assign` maybe?
```js
proto = Object.assign( Object.create(HTMLElement.prototype), basePrototype )
```

If that is a valid way to do this, I suggest something like this: c31f57b53e20d4951be3191da7870503e48a5cc4

**Comment by csuwildcat** [comment]
Ok, so to better understand: are you asking for a way to extend a native element, but have the tag not being an instance of the native element?

**Comment by csuwildcat** [comment]
Alright, I think it know what you're saying: currently if you extend and use both the X-Tag object definition AND your own prototype definition, it tosses out your proto and keeps only the X-Tag inflated proto?

If so, this should do it:

```javascript
      var extended = tag['extends'];
      var elementProto = win.HTMLElement.prototype;
      if (extended && basePrototype) {
        for (var z in basePrototype) tag.prototype[z] = basePrototype[z];
      }
      return doc.registerElement(_name, {
        'extends': extended,
        'prototype': extended ?
                        Object.create(
                          Object.create(doc.createElement(extended).constructor).prototype,
                          tag.prototype
                        ) :
                        basePrototype instanceof elementProto.constructor ?
                          basePrototype :
                          Object.create(elementProto, tag.prototype)
      });
```

**Comment by csuwildcat** [comment]
Here we go, one small change:

```javascript
      var extended = tag['extends'];
      if (basePrototype) {
        for (var z in basePrototype) tag.prototype[z] = basePrototype[z];
      }
      return doc.registerElement(_name, {
        'extends': extended,
        'prototype': extended ?
                        Object.create(
                          Object.create(doc.createElement(extended).constructor).prototype,
                          tag.prototype
                        ) :
                        Object.create(win.HTMLElement.prototype, tag.prototype)
      });
```

**Comment by csuwildcat** [comment]
That last one should cover all the bases:

- If you're not extending an element, it uses the HTMLElement proto by default (which is the only thing allowed in that case)

- If you're extending an element it automatically uses the prototype it is extending (which is again required)

- For both cases, it merges the prototype definitions so you can use BOTH the X-Tag object definition API and a raw prototype definition.

Make sense?

**Comment by csuwildcat** [comment]
I just pushed the latest mod out to that `custom-proto` branch: https://github.com/x-tag/core/tree/custom-proto

**Comment by kelvinss** [comment]
Does `tag.prototype[z] = basePrototype[z]` works? Because it seems `tag.prototype` is filled with ["property descriptors"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor)

**Comment by csuwildcat** [comment]
Both are supposed to be property descriptors, that was always the design.

**Comment by kelvinss** [comment]
`core.js:418 Uncaught TypeError: Property description must be an object: some_value`
:P

**Comment by kelvinss** [comment]
On the original code we have:
```js
var elementProto = basePrototype ?
            basePrototype :
AND
'prototype': Object.create(elementProto, tag.prototype)
```
`elementProto`(aka. `basePrototype`) is passed directly, and `tag.prototype` as "property descriptors"

**Comment by csuwildcat** [comment]
@kelvinss I just pulled in the code that allows for merging the X-Tag generated descriptor with a user-provided one.

**Pull request closed without merging**
