### PR TITLE
Fix integration with `WebReflection/document-register-element` polyfill

### PR DESCRIPTION
**Pull request by ramybenaroya**
fix for https://github.com/x-tag/core/issues/153

### CODE REVIEW

**Comment by csuwildcat** [comment]
Thank you for highlighting this, I didn't realize some polyfills/libraries were turning logic based on key presence. Can you check out what I just threw up on master: https://github.com/x-tag/core/blob/master/src/core.js#L411-L418

**Comment by csuwildcat** [comment]
I haven't pushed that out yet to NPM/Bower, so let me know if it works against your test cases. (it passes all of our tests)

**Comment by ramybenaroya** [comment]
Works great.

**Comment by ramybenaroya** [comment]
Fixed https://github.com/x-tag/core/commit/619d2b0b940b1439283b6d52002fddf63c7d5d7e

**Pull request closed without merging**
