### PR TITLE
Cross browser prefix detection

### PR DESCRIPTION
**Pull request by joao-arvins**
Updated logic to set prefix so that it works in all browsers.

### CODE REVIEW

**Comment by joao-arvins** [comment]
Fix for:

- https://github.com/x-tag/core/issues/172
- https://github.com/x-tag/core/issues/164

**Comment by joao-arvins** [comment]
@csuwildcat all the checks are now collapsed into a single regexp. Can you have a look when you have some time please?

Thanks

**Comment by joao-arvins** [comment]
Hi @csuwildcat . Did you had the opportunity to have a look at this pull request?

Cheers

**Comment by csuwildcat** [comment]
I did - I had that one last question before merging. Can you take a look and answer for me?

**Comment by joao-arvins** [comment]
Not sure about the question you're talking about. 
Is it the one about collapse all the checks into one single regexp? If so I've already updated it some weeks ago. Check the latest commit.

If not can you point me to the right direction?

Thanks

**Comment by toreholmberg** [comment]
Did this make it into the build?

**Pull request merged**
